name: Continuous Integration

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: "Download sandcastle"
        run: |
             $url = "https://github.com/EWSoftware/SHFB/releases/download/v2020.3.6.0/SHFBInstaller_v2020.3.6.0.zip"
             $output = "$pwd\Rail\SHFBInstaller_v2020.3.6.0.zip"
             $start_time = Get-Date
             (New-Object System.Net.WebClient).DownloadFile($url, $output)
             Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"
        shell: pwsh
        working-directory: .\Rail
      - uses: actions/checkout@master
      - name: "Setup .NET Core"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name:  "Build with dotnet"
        run: dotnet build --configuration Release
        working-directory: .\Rail
      - name: "Test"     
        run: dotnet test
        working-directory: .\Rail
