name: Continuous Integration

on: 
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        
    steps:
      - uses: actions/checkout@master
      - name: "Setup .NET Core"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name:  "Build with dotnet"
        run: dotnet build --configuration Release
        working-directory: .\Rail
      - name: "Test"     
        run: dotnet test
        working-directory: .\Rail
