name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019
    strategy:
      max-parallel: 2
      matrix:
        build_configuration: [Release]
        build_platform: [x86,x64]
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup to add MSBuild.exe to path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: restore
      working-directory: 
      run: msbuild Rail.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: MSBuild of solution
      working-directory: 
      run: msbuild Rail.sln /m /verbosity:minimal /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
          name: Rail (x64)
          path: ..\Rail.Installer\Installs\Rail-0.1.0.0-Release-x64.msi"
          
    - name: Archive artifacts
      uses: actions/upload-artifact@v1
      with:
          name: Rail (x32)
          path: ..\Rail.Installer\Installs\Rail-0.1.0.0-Release-x32.msi"


