name: Delivery Build

on: 
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 2
      matrix:
        build_platform: [x86, x64]
      
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Setup to add MSBuild.exe to path"
      uses: warrenbuckley/Setup-MSBuild@v1

    # - name: "Download sandcastle"
      # run: |
           # $url = "https://github.com/EWSoftware/SHFB/releases/download/v2020.3.6.0/SHFBInstaller_v2020.3.6.0.zip"
           # $output = "$pwd\Rail\SHFBInstaller_v2020.3.6.0.zip"
           # $start_time = Get-Date
           # (New-Object System.Net.WebClient).DownloadFile($url, $output)
           # Write-Output "Time taken: $((Get-Date).Subtract($start_time).Seconds) second(s)"
      # shell: pwsh
      # working-directory: .\Rail

    - name: "restore"
      working-directory: .
      run: dotnet restore Rail.sln
#      run: msbuild Rail.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

#    - name: "MSBuild of solution"
#      working-directory: .\Rail
#      run: msbuild Rail.sln /m /verbosity:minimal /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: "Build WIX"
      working-directory: .\Rail.Installer
      run: dotnet build Rail.Installer.wixproj -c "Release" -p:platform="${{ matrix.build_platform }}"

    - name: "Archive artifacts"
      uses: actions/upload-artifact@v1
      with:
          name: Rail (${{ matrix.build_platform }})
          path: Rail.Installer\Installs\Rail-0.1.0.0-Release-${{ matrix.build_platform }}.msi
