name: Delivery Build

on: 
  push:
    branches:
      - master

  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest
    strategy:
      max-parallel: 1
      matrix:
        build_configuration: [Release]
        build_platform: [x86,x64]
      
    steps:
    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Setup to add MSBuild.exe to path"
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: "restore"
      working-directory: .\Rail
      run: msbuild Rail.sln /m /verbosity:minimal /t:restore /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

#    - name: "MSBuild of solution"
#      working-directory: .\Rail
#      run: msbuild Rail.sln /m /verbosity:minimal /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: "Build WIX"
      working-directory: .\Rail
      run: msbuild Rail.Installer\Rail.Installer.wixproj /m /verbosity:minimal /p:configuration="${{ matrix.build_configuration }}" /p:platform="${{ matrix.build_platform }}"

    - name: "Archive artifacts"
      uses: actions/upload-artifact@v1
      with:
          name: Rail (${{ matrix.build_platform }})
          path: Rail.Installer\Installs\Rail-0.1.0.0-Release-${{ matrix.build_platform }}.msi
